name: Maven Package

on:
  release:
    types: [created]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 8
      uses: actions/setup-java@v2
      with:
        distribution: 'zulu'
        java-version: '8'
        java-package: jdk+fx
        server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
        settings-path: ${{ github.workspace }} # location for the settings.xml file
    - name: prepare mvn settings
      uses: s4u/maven-settings-action@v2.3.0
      with:
        servers: |
          [{
              "id": "github",
              "username": "${{ secrets.USER_PACKAGE_ALL }}",
              "password": "${{ secrets.TOKEN_PACKAGE_ALL }}"
          }]
    - name: Build with Maven
      run: mvn -B package -DskipTests --file pom.xml

    - name: Publish to GitHub Packages Apache Maven
      run: mvn deploy -DskipTests -s $GITHUB_WORKSPACE/settings.xml
      env:
        GITHUB_TOKEN: ${{ github.token }}
